
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_USER = "FETCH_USER";
export const USER_ERROR =  'USER_ERROR';
export const USER_PROFILE = "USER_PROFILE";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const FETCH_USER_PROFILE_ERROR = 'FETCH_USER_PROFILE_ERROR';
export const CHANGE_STATUS_ONE = "CHANGE_STATUS_ONE";
export const CHANGE_STATUS_ONE_ERROR = "CHANGE_STATUS_ONE_ERROR";
export const CHANGE_STATUS_TWO = "CHANGE_STATUS_TWO";
export const CHANGE_STATUS_TWO_ERROR = "CHANGE_STATUS_TWO_ERROR";
export const ADMIN_APPROVE = "ADMIN_APPROVE";
export const ADMIN_APPROVE_ERROR = "ADMIN_APPROVE_ERROR";
export const ADMIN_REJECT = "ADMIN_REJECT";
export const ADMIN_REJECT_ERROR = "ADMIN_REJECT_ERROR";
export const ADMIN_RESTART = "ADMIN_RESTART";
export const ADMIN_RESTART_ERROR = "ADMIN_RESTART_ERROR";
export const MATCH = 'MATCH';
export const MATCH_ERROR = "MATCH_ERROR";
export const ADMIN = "ADMIN";
export const ADMIN_ERROR = "ADMIN_ERROR";
export const PAYMENT = "PAYMENT";
export const PAYMENT_ERROR = "PAYMENT_ERROR";
export const BOOKING = "BOOKING";
export const BOOKING_ERROR = "BOOKING_ERROR";














